const citiesOnMap = [
    'Stockholm', 
    'Göteborg', 
    'Malmö', 'Kalmar', 
    'Jönköping', 
    'Visby', 
    'Karlstad', 
    'Gävle', 
    'Mora', 
    'Sundsvall', 
    'Östersund', 
    'Umeå', 
    'Luleå', 
    'Tärnaby', 
    'Kiruna'
]

const coordinatesForMap = {
    'Stockholm' : ['155px', '392px'],
    'Göteborg'  : ['20px', '455px'],
    'Malmö'     : ['45px', '542px'],
    'Kalmar'    : ['110px', '500px'],
    'Jönköping' : ['70px', '455px'],
    'Visby'     : ['160px', '465px'],
    'Karlstad'  : ['55px', '390px'],
    'Gävle'     : ['140px', '340px'],
    'Mora'      : ['90px', '330px'],
    'Sundsvall' : ['140px', '260px'],
    'Östersund' : ['90px', '230px'],
    'Umeå'      : ['185px', '200px'],
    'Luleå'     : ['210px', '130px'],
    'Tärnaby'   : ['95px', '130px'],
    'Kiruna'    : ['170px', '40px']   
}

const icons = [
    'fa-sun',
    'fa-cloud-sun',
    'fa-cloud-sun',
    'fa-cloud-sun',
    'fa-cloud-sun',
    'fa-cloud',
    'fa-cloud-smog',
    'fa-droplet',
    'fa-cloud-rain',
    'fa-cloud-showers-heavy',
    'fa-cloud-bolt',
    'fa-droplet',
    'fa-cloud-rain',
    'fa-cloud-showers-heavy',
    'fa-snowflake',
    'fa-snowflake',
    'fa-snowflake',
    'fa-droplet',
    'fa-cloud-rain',
    'fa-cloud-showers-heavy',
    'fa-cloud-bolt',
    'fa-snowflake',
    'fa-snowflake',
    'fa-snowflake',
    'fa-snowflake',
    'fa-snowflake',
    'fa-snowflake',
]